dist: focal
language: node_js
node_js:
 - "10"
 - "12"
 - "13"
 - "14"

jobs:
  include:
    - stage: deploy
      if: branch = master
      env:
        secure: B1LpOK7YIMDR6tHeQy/OppRa6wC57tugA67eZeAKPH/s+c7NUwrcaEMuya920+WGml3h13W2Tc2er62C/89tUiBSKceCav/tSzTaEDSjFvKVfCVOiGdp59f2EuB9Bii3bHPbNeX1GkuKICSgkseFfafkQK6CHNt1pP898xFaQWU8uM1iUJl/TrLHOPRKf3wZLduQR0AxQLFy1psX9zAnxXMHL43AlI2htaPy6yUXX8kIz8qGCMMtEmT7B8bHQsrD1+ahmPNe1WdrNQv0lOPbSTYbcBDHjh9O0NIuWzkrUk7DK18FsVR6iOFgdYkmUkWGzB+07SkhT62OYaiHviWX3xz08sAOahUvHwD4ijZMrMitbI/+DkdjFPeRUh7/l3Twrcw9QO4kgtQ5WBlS/QDBV7/FJXxjyepjfC1GQ7jYVzrAMgG6dQGBBvlJPqSaiipgGDQQuKfrHRS7Ppavb7fUyWmaIA2yZQQLjZAdxYZ0Nif0FgkjJ7EI3t8AqnBCr63vOBThe9qru4dljyRLMYihUMkv02RuVS7Y7c79a2tRml2sjlkC7Szgoxcq8sD7kcjYk20CVt5hZY357fzI8mqwmluCr3P7kYz4BoDsF5t0cM6rcsrvC7vVv+yZTGpmDfRGHgfO0y8keCyelRJxaP3SrCcYmBwwQ4L1QozNNiIzTiI=
      node_js: node
      script: skip
      before_deploy:
        - git fetch --unshallow
        - git checkout master
      deploy:
        provider: npm
        edge: true
        run_script: publish:ci
