dist: focal
language: node_js
node_js:
  - "10"
  - "12"
  - "13"
  - "14"

before_deploy:
  - git fetch --unshallow
  - git checkout master

jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: node
      script: skip
      deploy:
        provider: npm
        edge: true
        api_token:
          secure: 536H8eHmJx60Ke+aOJkkFig6qA1Mim2lsEUzx5ue3dyMSkOI56WBVFG2iKOMxwzh4fSnyR1aZD1mUGyDjl8yt95OfDx+BFkV/HRES5F1xLldczXpUR5Wyy2oLozBNnIuvEr6JVSWyKhAszNQ4404JztN6NnliQb3Cr+J6K1/GAhptjd7nYMuzqlGLI02hX8IBSSx/ZojEUS0Mg3XNH1B8dQA6IgNQx45AO02UtdvHMoEAUsb4WjMjtRa8TDtEX1uOqqihy0yBJXn4lLrScT2wkDK8z+FUhKlS6QCmAmS1dk2mpPuzInZ89kXv8ABX0bSI2ccx8dypFfwT3Sl7JXJ4TX116J5n3R3rZ2ndXFZoI+v6YVDvfsI4neQbAeessLX794Rol1HFiKTc4xFD4h0yB16Z9s7L2RhHciNtRoUkBPCVFPe34PSQpW5AA/jX2lIDmPyvmau7x1GCOPQNXljjc50w9FueFeSb/4j6ogMlywxGm+gmB4F846lGqHZ7/fj++jbNRVwvtSBnWyP0aJEf1boo6lTNubQ3uj+aR4v/rdGecoWT9+5AXdgIXrB6azWxLnV2iDedYVDhFF1MHL2WciJYZ+4Qun2aV5oQvwE+4FiSygSozsNPaDDh54LytijlScPhvvJ/y0hGQz9Vd+ObUPFKW3vs4XBwGz3cpgi/As=
        run_script: publish:ci
