dist: focal
language: node_js
node_js:
 - "10"
 - "12"
 - "13"
 - "14"

jobs:
  include:
    - stage: deploy
      if: branch = master
      env:
        secure: tDGkexlwhJMnrRaOR+CeECIvvT7uD/4hfyYwdt3QA8si7DflTulmDy7kGKNBwUCml7GxLGNyHw71R3NcLKwh5lKoNz8JBjFQRudm/LwLMMkKvxMczvMdUmkA7R3btoFgHDFypbOjvvMtxRcfaSWhCe1IGPkQ5a9GGSO/Ded2C1jsmD7CIel9XnC4UX/xgD4oZZ5NiPPs1kdmxB5NlwbTst8VpGXW+KTCSl7AwP9U/KQrKolKOkqy1RDqtlvKQn9EaWCgpJvTjmq1ElrYcpG+Mx0CqCm0h5MPvm9rmdYbvwBPGBE/tuDTCr4OZJs8Zla/exTdTt91NHfjJ8zMk24a9iHsPJoTLYAiioIkI/FUGRXpJnvwwbOzD+4Cfj4iK9VnOLLw+MAnoqsuwhtQmhHU02K0Lx28Dyx9eviMJmB29Qhc5pc6P2MXCWGKwcNzJ7xCNdV2ePm/TCrVsxfhUhCR5ViufZOsGAI3G7y/qW+AInHNMHT97fYpCuuDE5/4WNjW4DhwfC8p8rKYdIvJAxRBdx/mXFj3XhkVAxuWiFFfodcU8fODWuBFJsS6uV15X39MpX55pdBYPCP6TYBzoopn2Fkzu9IjcPswQ/fkLKH27WmZhdTW6YKMQXoMM9OrDp5W4+26N0bNoidn1LLYA6+TRcbrLYTcx9tRr0f204RU2pU=
      node_js: node
      script: skip
      before_deploy:
        - git fetch --unshallow
        - git checkout master
      deploy:
        provider: npm
        edge: true
        run_script: publish:ci
