dist: focal
language: node_js
node_js:
 - "10"
 - "12"
 - "13"
 - "14"

jobs:
  include:
    - stage: deploy
      if: branch = master
      env:
        - secure: b7GX8bn6gp8ajOUkXQ1pO67XhyrwzsuN3FlD2M7zyA54CG8+xoYWfa4IYfwO/mX2JTeq8Kr2PJAwhzSINYeVoXnCXqjGxSFJI7rEBVBotOFmhANmKiR7kw/9wW3b4ka0lx4Am7am8CVI3LHhKSah/P49HnlbQHaCMvY78jIBEudS3bnvM3jdsWKlmW41e/Q3gsGqtn2HBkmvwe8W1BU4GA1U66UbJRIy6L+3m0xZ689fuFB5YL9GCUkiEQF51nhyPXL5JJxKt4BXGxwwVKAOZeyS/W8i/UWhZV4KF+3PYet0nzPgTIDbk1O7k4NpX4b6jmDjOWUIdRpb0R2tN/JZ3cGIjmwP5c35jwvIOU+oRVkU1f1HhZ10LZbCStwnSlsFt3n+xLQ6LBlaRMY4CnBmSu88k9gfQDIvo4FXDUVSRhpDfCggEeHQwyQprZcgqCSADpoYlwZauxELoFTC/nhm4Bx+tH9AQsIoQ+PMSZQuubaaaJuoap7zF7lJbfx89D5K27QQ3SoYYC5BZV0Nv1RM9cdCIGcwan51Ky1+BYs8Xq4Qf28bWhh9Y9pYQhD2bEIGOF4aP8kJPPa05MsAJsm0UKH3cQHYOR0+7oXs9yzljpMyr7s2+drtenCy8dvrJrLp9UA9OMr7gJV9wA9w6zzyT+zWnhvm6H95sq+zszwn7jQ=
      node_js: node
      script: skip
      before_deploy:
        - git fetch --unshallow
        - git checkout master
      deploy:
        provider: npm
        edge: true
        run_script: publish:ci
